### ISSUE TITLE
HTTP 503 – Service Unavailable – craft\web\ServiceUnavailableHttpException

### ISSUE THREAD

**Issue by alexgit2k** [craftcms/happy-lager#35]
### Description

Calling homepage in browser says:
```

craft\web\ServiceUnavailableHttpException in craftcms/application/vendor/craftcms/cms/src/web/Application.php:683
Stack trace:
#0 craftcms/application/vendor/craftcms/cms/src/web/Application.php(213): craft\web\Application->_processUpdateLogic()
#1 craftcms/application/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#2 craftcms/application/web/index.php(21): yii\base\Application->run()
#3 {main}
Copy StacktraceSearch StackoverflowSearch GoogleException
HTTP 503 – Service Unavailable – craft\web\ServiceUnavailableHttpException
1. in craftcms/application/vendor/craftcms/cms/src/web/Application.phpat line 683
674675676677678679680681682683684685                $actionSegments === ['app', 'migrate'] ||
                $actionSegments === ['pluginstore', 'install', 'migrate']
            ) {
                return $this->runAction(implode('/', $actionSegments));
            }
        }
 
        // If an exception gets throw during the rendering of the 503 template, let
        // TemplatesController->actionRenderError() take care of it.
        throw new ServiceUnavailableHttpException();
    }
}
2. in craftcms/application/vendor/craftcms/cms/src/web/Application.php at line 213– craft\web\Application::_processUpdateLogic()
207208209210211212213214215216217218219                throw new ServiceUnavailableHttpException();
            }
 
            // getIsCraftDbMigrationNeeded will return true if we're in the middle of a manual or auto-update for Craft itself.
            // If we're in maintenance mode and it's not a site request, show the manual update template.
            if ($this->getUpdates()->getIsCraftDbMigrationNeeded()) {
                return $this->_processUpdateLogic($request) ?: $this->getResponse();
            }
 
            // If there's a new version, but the schema hasn't changed, just update the info table
            if ($this->getUpdates()->getHasCraftVersionChanged()) {
                $this->getUpdates()->updateCraftVersionInfo();
 
3. in craftcms/application/vendor/yiisoft/yii2/base/Application.php at line 392– craft\web\Application::handleRequest()
4. in craftcms/application/web/index.php at line 21– yii\base\Application::run()
15161718192021    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}
 
// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
Yii Framework
2021-08-06, 15:13:35

nginx/1.20.1

Yii Framework/2.0.42.1
```

### Steps to reproduce

1. Setup
```
git clone https://github.com/craftcms/demo.git application
cd application
composer install
cp .env.example .env
sed -i 's/DB_DATABASE=.*/DB_DATABASE=craftcms/' .env
sed -i 's/DB_USER=.*/DB_USER=craftcms/' .env
sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=craftcms/' .env
sed -i 's|SITE_URL=.*|SITE_URL=https://craftcms.xxx.yyy|' .env
php craft setup/security-key
mysql craftcms < happylager.sql
```
2. Call https://craftcms.xxx.yyy

### Additional info

- Craft version: latest version of happy-lager 
- PHP version: 7.4.22
- Database driver & version: MariaDB 10.6
- Plugins & versions:

**Comment by alexgit2k** [comment]
Not able to reproduce it anymore.
